Feature: adding oauth2 login test for wrong credentials
eapg/ea_restaurant_data_loader pull request #17
Opened 2023-12-26 23:01 UTC by eapg

* Refactoring `validate client credentials function` to catch condition when app client is not found due wrong credentials.
* Adding test for oauth2 login wrong credentials.

2023-12-26 23:33 UTC, reynoldmorel requested changes

2023-12-26 23:33 UTC, reynoldmorel commented on lib/services/oauth2_service.ex
>      end
```
validated_client =
  case client do
    %AppClient{} -> client
    _ -> raise InvalidCredentialsError
  end

password_struct = ApplicationUtil.build_password_type_from_env(client_secret, client.client_secret)

case PasswordEncoder.validate_password(password_struct) do
  true -> {:ok}
  _ -> raise InvalidCredentialsError
end
```

2023-12-27 00:27 UTC, eapg commented on lib/services/oauth2_service.ex
>      end
Done.

2023-12-27 00:38 UTC, reynoldmorel approved these changes

2023-12-27 01:08 UTC, merged